version: "3"
services:
  api:
    image: kimsee/plain:latest
    volumes:
      - ./src/main/resources:/app/config
    environment:
        SPRING_CONFIG_LOCATION: file:/app/config/application.yml

#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://15.164.26.240:3310/plain
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_DATA_REDIS_HOST: 15.164.26.240
#      SPRING_DATA_REDIS_PORT: 3101
    ports:
      - "8010:8080"
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "3101:6379"  # Fixed Redis port
    container_name: plain-redis
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - backend

  mysql:
    image: kimsee/plain_mysql
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql_plain
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=plain
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul  # Fixed spacing issue
    volumes:
      - mydb_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mydb_data: {}
  redis_data: {}

networks:
  backend:
    driver: bridge