version: "3"
services:
  api:
    image: plain:latest
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8010:8080"
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "3101:6379"
    container_name: plain-redis
    volumes:
      - C:\Users\user\Desktop\Back\docker\plain:/var/lib/redis
    networks:
      - backend

  mysql:
    image: kimsee/plain_mysql:latest
    restart: always
    command:
        - --lower_case_table_names=1
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    container_name: mysql_plain
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=plain
      - MYSQL_ROOT_PASSWORD=1234
      - TZ = Asia/Seoul
    volumes:
      - C:\Users\user\Desktop\Back\docker\plain_my:/var/lib/mysql
    networks:
      - backend
networks:
    backend:
      driver: bridge
